service: meeting-scheduler
useDotenv: true

frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin  # dotenv plugin to load .env variables
  - serverless-esbuild
  - serverless-offline


custom:
  dotenv:
    path: .env
    logging: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    API_TOKEN: ${env:API_TOKEN}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/MeetingDetails

functions:

  authorizer:
    handler: src/functions/authorizer.handler

  registerMeeting:
    handler: src/functions/handler.registerMeeting
    events:
      - http:
          path: schedule-meeting
          method: post
          cors: true
          authorizer:
            name: authorizer
            type: token
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 300

resources:
  Resources:
    MeetingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: MeetingDetails
        AttributeDefinitions:
          - AttributeName: "meetingId"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "meetingId"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST
